# Generated by Django 4.2.7 on 2023-12-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0002_credit_term_months_from_enum_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="term_months_from_enum",
        ),
        migrations.AlterField(
            model_name="credit",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="credit",
            name="term_months",
            field=models.PositiveIntegerField(),
        ),
    ]
