# Generated by Django 4.2.7 on 2023-12-20 07:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(default="Test", max_length=100)),
                ("account_no", models.CharField(max_length=16, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_deposit_allowed", models.BooleanField(default=True)),
                ("deposit_pending", models.BooleanField(default=False)),
                ("cvv_code", models.CharField(max_length=3)),
                (
                    "card_type",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("U", "USD"), ("B", "BYN")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        choices=[("U", "USD"), ("B", "BYN")], max_length=1
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("deposit_pending", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SavingsGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_name", models.CharField(max_length=255, unique=True)),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.date(2024, 1, 19)
                            )
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="userbankaccount",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BankAccountType",
        ),
    ]
