# Generated by Django 4.2.7 on 2023-12-20 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "transactions",
            "0002_alter_transaction_options_remove_transaction_account_and_more",
        ),
        ("accounts", "0002_card_payment_savingsgoal_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserBankAccount",
        ),
        migrations.AddField(
            model_name="savingsgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card_payments",
                to="accounts.card",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
