# Generated by Django 4.2.7 on 2023-12-20 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_budgetsystem_card_daily_balance_card_fixated_sum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetsystem",
            name="daily_percent",
            field=models.PositiveIntegerField(
                default=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="budgetsystem",
            name="savings_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="savings_card",
                to="accounts.card",
            ),
        ),
    ]
