# Generated by Django 4.2.7 on 2023-12-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_budgetsystem_daily_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budgetsystem",
            name="redirect_savings",
        ),
        migrations.AlterField(
            model_name="budgetsystem",
            name="savings_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="savings_card",
                to="accounts.card",
            ),
        ),
    ]
