# Generated by Django 4.2.7 on 2023-12-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_card_payment_savingsgoal_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="balance_after_transaction",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_card",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_transactions",
                to="accounts.card",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_card",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_transactions",
                to="accounts.card",
            ),
        ),
    ]
